title: user lborruto
description: this is me
baseurl: ""
url: ""

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

color_bg: gray-9        # Dark background
color_punct: cyan-6     # Punctuation
color_key: green-5      # Keys
color_value: magenta-6  # Values
color_hover: yellow-5   # Hover effect